apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp # match key,value pairs
  ports:
  - port: 80
    nodePort: 30080  # only for NodePort
  type: NodePort