name: Deploy to Server

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.11
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          cd /workspace
          git pull origin main